<a href="https://colab.research.google.com/github/yusi0928/data-prework/blob/master/L_W2D5_Data_Aggregation_and_Summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

vehicles = pd.read_csv('vehicles.csv')
vehicles.groupby(['Transmission'])

In [0]:
#Here we aggregate 3 different columns and compute their mean based on the different transmission values
vehicles.groupby(['Transmission'])['Highway MPG', 'City MPG', 'Combined MPG'].mean()

vehicles.groupby(['Transmission'])['Highway MPG', 'City MPG', 'Combined MPG'].mean().reset_index()

                        Transmission  Highway MPG   City MPG  Combined MPG
0                          Auto (AV)    40.000000  35.000000     37.000000
1                       Auto (AV-S6)    25.000000  22.000000     23.000000
2                       Auto (AV-S8)    22.000000  20.000000     21.000000
3                           Auto(A1)    37.000000  41.000000     39.000000
4                        Auto(AM-S6)    32.978261  24.315217     27.554348
5                        Auto(AM-S7)    25.300781  17.746094     20.425781
6                        Auto(AM-S8)    32.000000  23.666667     26.666667
7                        Auto(AM-S9)    22.000000  21.000000     21.000000
8                          Auto(AM5)    39.000000  33.666667     36.000000
9                          Auto(AM6)    31.345455  23.909091     26.736364
10                         Auto(AM7)    22.382166  16.248408     18.420382
11                         Auto(AM8)    28.600000  22.400000     24.600000
12                       Auto(AV-S6)    30.800000  25.944828     27.848276
13                       Auto(AV-S7)    33.746032  27.952381     30.206349
14                       Auto(AV-S8)    28.538462  22.846154     24.961538
15                          Auto(L3)    17.000000  14.000000     15.500000
16                          Auto(L4)    19.000000  13.500000     15.500000
17                    Automatic (A1)    31.666667  34.000000     32.666667
18                    Automatic (A6)    21.000000  14.000000     16.500000
19                   Automatic (AM5)    41.000000  33.000000     36.000000
20                   Automatic (AM6)    18.000000  13.000000     15.000000
21                    Automatic (AV)    30.000000  21.750000     24.750000
22                 Automatic (AV-S6)    27.777778  23.666667     25.222222
23                    Automatic (S4)    24.768559  18.074236     20.528384
24                    Automatic (S5)    24.205596  17.087591     19.698297
25                    Automatic (S6)    25.938807  18.337514     21.096921
26                    Automatic (S7)    23.605364  16.804598     19.195402
27                    Automatic (S8)    26.983333  18.450000     21.500000
28                    Automatic (S9)    28.307692  19.923077     23.038462
29  Automatic (variable gear ratios)    31.094815  27.460741     28.777778
30                   Automatic 3-spd    21.630343  17.449750     19.033500
31                   Automatic 4-spd    21.691639  15.944261     18.042607
32                   Automatic 5-spd    21.647167  15.445417     17.693229
33                   Automatic 6-spd    23.768156  16.720670     19.237430
34                    Automatic 6spd    34.000000  21.000000     26.000000
35                   Automatic 7-spd    24.413897  17.117825     19.746224
36                   Automatic 8-spd    24.448560  16.576132     19.279835
37                   Automatic 9-spd    28.366667  20.077778     23.200000
38                      Manual 3-spd    16.945946  14.229730     15.256757
39                      Manual 4-spd    21.042113  16.871363     18.462481
40                      Manual 5 spd    14.000000  14.000000     14.000000
41                      Manual 5-spd    25.664312  19.242327     21.634391
42                      Manual 6-spd    26.202229  18.306232     21.153941
43                      Manual 7-spd    26.205882  18.220588     21.117647
44                        Manual(M7)    22.333333  14.000000     17.000000

In [0]:
#In this example we aggregate based on two columns and 
#compute the median CO2 Emission for all combinations of fuel type and cylinders
#vehicles.groupby(['Fuel Type', 'Cylinders'])['CO2 Emission Grams/Mile'].median()

vehicles.groupby(['Fuel Type', 'Cylinders'])['CO2 Emission Grams/Mile'].agg(['median','mean'])

                                           median        mean
Fuel Type                   Cylinders
CNG                         4.0        253.197321  257.539637
                            6.0        417.030882  417.030882
                            8.0        568.070913  573.309895
Diesel                      4.0        308.484848  330.909525
                            5.0        391.538462  425.288362
                            6.0        439.000000  435.797518
                            8.0        598.823529  589.949213
                            10.0       598.823529  590.506536
Gasoline or E85             4.0        355.480000  359.073842
                            6.0        444.350000  454.282739
                            8.0        592.466667  594.649022
Gasoline or natural gas     4.0        386.391304  383.464097
                            6.0        437.000000  437.000000
                            8.0        740.583333  768.310391
Gasoline or propane         8.0        666.525000  666.525000
Midgrade                    6.0        416.000000  406.800000
                            8.0        527.000000  524.891046
Premium                     2.0        493.722222  486.635300
                            3.0        246.861111  253.485043
                            4.0        386.391304  389.573558
                            5.0        444.350000  436.029637
                            6.0        444.350000  454.941429
                            8.0        522.764706  560.324585
                            10.0       634.785714  646.760443
                            12.0       683.615385  698.033195
                            16.0       888.700000  873.062500
Premium Gas or Electricity  2.0         40.000000   39.000000
                            4.0         89.000000   96.000000
                            6.0        260.000000  259.333333
                            8.0        277.000000  277.000000
Premium and Electricity     3.0        198.000000  198.000000
                            4.0        214.000000  206.333333
                            6.0        228.000000  235.333333
                            8.0        463.000000  463.000000
Premium or E85              4.0        373.000000  368.142857
                            6.0        423.190476  423.276621
                            8.0        504.000000  524.687500
                            12.0       633.892857  624.215035
Regular                     2.0        522.764706  513.925689
                            3.0        247.000000  246.518217
                            4.0        386.391304  381.906539
                            5.0        467.736842  452.069902
                            6.0        493.722222  506.475468
                            8.0        634.785714  636.099229
                            10.0       776.500000  776.748106
                            12.0       683.615385  712.338223
Regular Gas and Electricity 4.0        129.000000  125.687500
Regular Gas or Electricity  4.0         51.000000   51.000000

In [0]:
#Here we produce the mean, median and standard deviation for combined MPG grouped by fuel type
vehicles.groupby(['Fuel Type'])['Combined MPG'].agg(['mean', 'median', 'std'])

                                  mean  median       std
Fuel Type
CNG                          18.133333    14.5  7.436663
Diesel                       23.488474    21.0  7.054702
Gasoline or E85              17.572385    17.0  3.822538
Gasoline or natural gas      15.350000    12.0  5.343712
Gasoline or propane          13.500000    13.5  1.603567
Midgrade                     17.378378    17.0  1.848381
Premium                      19.343816    19.0  4.097972
Premium Gas or Electricity   31.647059    33.0  7.158397
Premium and Electricity      26.300000    25.5  5.141165
Premium or E85               20.090909    20.0  3.676502
Regular                      20.144698    20.0  5.317500
Regular Gas and Electricity  41.937500    38.5  5.246824
Regular Gas or Electricity   42.000000    42.0  0.000000

In [0]:
# custom aggregation function
from scipy import stats

def agg_mode(x):
    return(stats.mode(x)[0])
def agg_freq(x):
    return(stats.mode(x)[1])

In [0]:
# show most common Vehicle Class per Transmission
vehicles.groupby("Transmission")["Vehicle Class"].agg([agg_mode, agg_freq])
#vehicles.groupby("Transmission")["Vehicle Class"].agg([stats.mode])


vehicles.groupby("Transmission")["Vehicle Class"].agg([agg_mode, agg_freq, 'min'])

,agg_mode,agg_freq,min
Transmission,,,
Auto (AV),Compact Cars,2,Compact Cars
Auto (AV-S6),Compact Cars,1,Compact Cars
Auto (AV-S8),Midsize Cars,1,Midsize Cars
Auto(A1),Subcompact Cars,1,Subcompact Cars
Auto(AM-S6),Compact Cars,37,Compact Cars
Auto(AM-S7),Minicompact Cars,75,Compact Cars
Auto(AM-S8),Compact Cars,3,Compact Cars
Auto(AM-S9),Two Seaters,1,Two Seaters
Auto(AM5),Two Seaters,12,Two Seaters
Auto(AM6),Compact Cars,33,Compact Cars
Auto(AM7),Two Seaters,89,Compact Cars
Auto(AM8),Standard Sport Utility Vehicle 4WD,3,Compact Cars
Auto(AV-S6),Midsize Cars,30,Compact Cars
Auto(AV-S7),Midsize Cars,19,Compact Cars
Auto(AV-S8),Midsize Cars,12,Compact Cars
Auto(L3),Special Purpose Vehicles,2,Special Purpose Vehicles
Auto(L4),Special Purpose Vehicles,2,Special Purpose Vehicles
Automatic (A1),Subcompact Cars,3,Subcompact Cars
Automatic (A6),Compact Cars,2,Compact Cars
Automatic (AM5),Two Seaters,2,Two Seaters
Automatic (AM6),Two Seaters,1,Two Seaters
Automatic (AV),Midsize Cars,2,Compact Cars
Automatic (AV-S6),Compact Cars,2,Compact Cars
Automatic (S4),Compact Cars,52,Compact Cars
Automatic (S5),Compact Cars,210,Compact Cars
Automatic (S6),Midsize Cars,498,Compact Cars
Automatic (S7),Midsize Cars,74,Compact Cars
Automatic (S8),Midsize Cars,199,Compact Cars
Automatic (S9),Small Sport Utility Vehicle 4WD,14,Compact Cars
Automatic (variable gear ratios),Midsize Cars,147,Compact Cars
Automatic 3-spd,Compact Cars,460,Compact Cars
Automatic 4-spd,Midsize Cars,1168,Compact Cars
Automatic 5-spd,Sport Utility Vehicle - 4WD,362,Compact Cars
Automatic 6-spd,Sport Utility Vehicle - 2WD,203,Compact Cars
Automatic 6spd,Midsize Cars,1,Midsize Cars
Automatic 7-spd,Compact Cars,110,Compact Cars
Automatic 8-spd,Large Cars,74,Large Cars
Automatic 9-spd,Small Sport Utility Vehicle 4WD,31,Compact Cars
Manual 3-spd,Vans,32,Standard Pickup Trucks
Manual 4-spd,Standard Pickup Trucks,439,Compact Cars
Manual 5 spd,Vans,1,Vans
Manual 5-spd,Compact Cars,1552,Compact Cars
Manual 6-spd,Compact Cars,508,Compact Cars
Manual 7-spd,Minicompact Cars,61,Minicompact Cars
Manual(M7),Two Seaters,3,Two Seaters